A Gentle Introduction to torch.autograd

In [ ]:
import torch
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)
y = a+b
z=x*y
print(f"y: {y}, z: {z}")
print(f"grad_fn for z: {z.grad_fn}")
print(f"grad_fn for y: {y.grad_fn}")
print(f"grad_fn for a: {a.grad_fn}")

#Element-wise product *
a= torch.tensor([[1,2],[3,4]])
b= torch.tensor([[10,20],[30,40]])
element_wise_product = a*b
print(f"Element-wise product:\n{element_wise_product}")

#Matrix product (@)
w= torch.tensor([[1,2,4],[3,4,3]])
v= torch.tensor([[1,2],[3,4],[5,6]])
matrix_product = w@v
print(f"Matrix product:\n{matrix_product}")

#reduction that reduces the tensor to a smaller number of elements
#dim argumrent specifies the dimension along which the reduction is performed
scores = torch.tensor([[1.0,20,3.0],[4.0,50,6.0]])
avg_per_assignmnet = scores.mean(dim=0)
print(f"Average per assignment:\n{avg_per_assignmnet}")
avg_per_student = scores.mean(dim=1)
print(f"Average per student:\n{avg_per_student}")

#Torch.Argmax
best_indices = torch.argmax(scores,dim=1)
print(best_indices)
#torch.gather
data= torch.tensor([[10,20,30],[40,50,60],[70,80,90]])
indices = torch.tensor([[2],[0],[1]])
gatherd=torch.gather(data,dim=1,index=indices)
print(gatherd)



y: 5.0, z: 20.0
grad_fn for z: <MulBackward0 object at 0x000001A9BFFEA980>
grad_fn for y: <AddBackward0 object at 0x000001A9BFFE8040>
grad_fn for a: None
Element-wise product:
tensor([[ 10,  40],
        [ 90, 160]])
Matrix product:
tensor([[27, 34],
        [30, 40]])
Average per assignment:
tensor([ 2.5000, 35.0000,  4.5000])
Average per student:
tensor([ 8., 20.])
tensor([1, 1])
tensor([[30],
        [40],
        [80]])


In [ ]:
#the forward pass
#making a guess
import torch

N = 10
D_in = 1
D_out=1

X =torch.randn(N,D_in)
true_w = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)
y_true= X @ true_w +true_b + torch.randn(N,D_out)*0.1

w = torch.randn(D_in,D_out, requires_grad=True)
b = torch.randn(D_out, requires_grad=True)

y_pred = X @ w + b
print(f"Predicted y: {y_pred[:3]}")
print(f"True y: {y_true[:3]}")
error = y_pred - y_true
square_E = error**2
loss = square_E.mean()
print(f"Loss: {loss}")


Predicted y: tensor([[-0.0059],
        [-0.4721],
        [ 0.6399]], grad_fn=<SliceBackward0>)
True y: tensor([[ 1.1980],
        [-0.2810],
        [ 3.1275]])
